# Generated by Django 3.1.4 on 2021-01-16 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210115_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nintendo_switch_code',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(999999999999), django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
