# Generated by Django 3.1.4 on 2021-01-17 04:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210116_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
    ]
