# Generated by Django 3.1.4 on 2021-01-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210116_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
