# Generated by Django 3.1.4 on 2021-01-17 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.game'),
        ),
    ]
