# Generated by Django 3.1.4 on 2021-01-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
