# Generated by Django 3.1.4 on 2021-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210120_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='avatar',
            field=models.ImageField(blank=True, default='games/avatar/default.png', upload_to='games/avatar'),
        ),
        migrations.AddField(
            model_name='game',
            name='header',
            field=models.ImageField(blank=True, default='games/header/default.png', upload_to='games/header'),
        ),
    ]
