# Generated by Django 3.1.4 on 2021-01-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210120_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.game'),
        ),
    ]
